config/routes.rb
Rails.application.routes.draw do
  resources :shirts
  devise_for :users
  root "pages#home"
  get 'dashboard' => "pages#dashboard"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, :all
    can :manage, :all

    # Shirt do |shirt|
    #   shirt.try(:user) == user
    #  end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  extend FriendlyId
    friendly_id :inscription, use: :slugged

  belongs_to :user
  has_attached_file :image
  has_attached_file :resource

validates_attachment_content_type :image,
content_type:  /^image\/(png|gif|jpeg)/,
message: "tylko obrazki pacanku"

validates_attachment_content_type :resource,
content_type: ['application/pdf'],
message: "tylko pdfki dupeczko"

validates :image, attachment_presence: true
validates :resource, attachment_presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :shirts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protect_from_forgery with: :exception
 rescue_from CanCan::AccessDenied do |exception|
   redirect_to root_path, notice: "nie ma edytowanka bez logowanka"
 end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
    redirect_to shirts_path
    end
  end

  def dashboard
    @shirts = current_user.shirts
  end


end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_shirt, only: [:show, :edit, :update, :destroy]

  # GET /shirts
  # GET /shirts.json

  def index
    @shirts = Shirt.where(availability: true)
  end

  # GET /shirts/1
  # GET /shirts/1.json
  def show
  end

  # GET /shirts/new
  def new
    @shirt = Shirt.new
  end

  # GET /shirts/1/edit
  def edit
  authorize! :manage, @book

  end

  # POST /shirts
  # POST /shirts.json
  def create
    @shirt = current_user.shirts.new(shirt_params)
    @shirt.save
    # respond_with(@shirt)

    respond_to do |format|
      if @shirt.save
        format.html { redirect_to @shirt, notice: 'Shirt was successfully created.' }
        format.json { render :show, status: :created, location: @shirt }
      else
        format.html { render :new }
        format.json { render json: @shirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shirts/1
  # PATCH/PUT /shirts/1.json
  def update
      authorize! :manage, @book
    respond_to do |format|
      if @shirt.update(shirt_params)
        format.html { redirect_to @shirt, notice: 'Shirt was successfully updated.' }
        format.json { render :show, status: :ok, location: @shirt }
      else
        format.html { render :edit }
        format.json { render json: @shirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shirts/1
  # DELETE /shirts/1.json
  def destroy
      authorize! :manage, @book
    @shirt.destroy
    respond_to do |format|
      format.html { redirect_to shirts_url, notice: 'Shirt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shirt
      @shirt = Shirt.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shirt_params
      params.require(:shirt).permit(:inscription, :size, :color, :price, :availability, :image, :resource)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Eshirt of Luke", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
      <!-- <li><%= link_to "koszuliny", "#" %></li> -->
      <li><%= link_to "koszuliny", shirts_path %></li>

      <% if current_user %>
      <li><%= link_to "dashboard", dashboard_path %></li>
      <li><%= link_to "ustawienia", edit_user_registration_path %></li>
      <li><%= link_to "spadówka", destroy_user_session_path, method: :delete %>

      <% else %>

        <li><%= link_to "zapiska", new_user_session_path %></li>

      <% end %>

      <li>

      </li>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eshirt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
  <button class="close" data-dismiss="alert">x</button>
  <%= message %>
  </div>
  <% end %>

<%= render "layouts/header" %>
<%= yield %>

</body>
</html>

app/views/pages/dashboard.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'nowa koszulina', new_shirt_path, class: "btn btn-primary" %>
<br>

<h1>koszuliny </h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>napis</th>
      <th>rozmiar</th>
      <th>kolor</th>
      <th>cena</th>
      <th>dostępność</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shirts.each do |shirt| %>
      <tr>
        <td><%= shirt.inscription %></td>
        <td><%= shirt.size %></td>
        <td><%= shirt.color %></td>
        <td><%= shirt.price %></td>
        <td><%= shirt.availability %></td>
        <td><%= link_to 'pokapoka', shirt %></td>
        <td><%= link_to 'edytowanko', edit_shirt_path(shirt) %></td>
        <td><%= link_to 'usuwanko', shirt, method: :delete, data: { confirm: 'pewniak?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/home.html.erb
<div class="jumbotron">
<h1>witaj w oglądarce koszulin</h1>
<p>tylko tu kupisz znane: "moja matka to świnia"</p>
<%= link_to "koszuliny", shirts_path, class: "btn btn-primary btn-block" %>
<%= link_to "zapiska", new_user_registration_path, class: "btn btn-primary btn-block" %>
</div>

app/views/shirts/_form.html.erb
<%= simple_form_for(@shirt) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :inscription %>
    <%= f.input :size %>
    <%= f.input :color %>
    <%= f.input :price %>
    <%= f.input :availability %>

    <%= f.input :image %>
    <%= f.input :resource %>  
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shirts/_shirt.html.erb
<div class="col-md-3">
<div class="thumbnail">
<%= link_to shirt_path(shirt) do %>
<%= image_tag shirt.image, class: "img-responsive" %>
<% end %>

<div class="caption">
<h3><%= link_to shirt.inscription, shirt_path(shirt) %></h3>
<p><%= shirt.price  %></p>
</div>
</div>
</div>

app/views/shirts/edit.html.erb
<h1>Editing Shirt</h1>

<%= render 'form' %>

<%= link_to 'Show', @shirt %> |
<%= link_to 'Back', shirts_path %>

app/views/shirts/index.html.erb
<div class="row">
<%= render @shirts %>
</div>

app/views/shirts/index.html_old.erb
<p id="notice"><%= notice %></p>



<%= link_to 'nowa koszulina', new_shirt_path, class: "btn btn-primary" %>
<br>

<h1>koszuliny </h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>napis</th>
      <th>rozmiar</th>
      <th>kolor</th>
      <th>cena</th>
      <th>dostępność</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shirts.each do |shirt| %>
      <tr>
        <td><%= shirt.inscription %></td>
        <td><%= shirt.size %></td>
        <td><%= shirt.color %></td>
        <td><%= shirt.price %></td>
        <td><%= shirt.availability %></td>
        <td><%= link_to 'pokapoka', shirt %></td>
        <td><%= link_to 'edytowanko', edit_shirt_path(shirt) %></td>
        <td><%= link_to 'usuwanko', shirt, method: :delete, data: { confirm: 'pewniak?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shirts/new.html.erb
<h1>New Shirt</h1>

<%= render 'form' %>

<%= link_to 'Back', shirts_path %>

app/views/shirts/show.html.erb
<div class="container">
<div class="row">

<div class="col-md-6">
<%= image_tag @shirt.image, class: "img-responsive" %>
</div>

<div class="col-md-6">
  <ul class="list-group">
  <li class="list-group-item"><%= @shirt.inscription %></li>
  <li class="list-group-item"><%= @shirt.color %></li>
  <li class="list-group-item"><%= @shirt.size %></li>
  <li class="list-group-item"><%= @shirt.price.to_f / 100 %> zlociszy</li>
  <li class="list-group-item"><%= link_to "edytowanko", edit_shirt_path(@shirt)  %>
   | <%= link_to "nazad", shirt_path  %> | <%= link_to "nastepna", shirt_path.next  %></li>
</ul>


</div>

</div>
</div>